### ISSUE TITLE
Desktop background and sidebar display artifacts when switching back to "internal"

### ISSUE THREAD

**Issue by tominglis** [hertg/egpu-switcher#36] opened 2020-05-28 09:32 UTC
**Context:**

I have a clean install of Ubuntu 20.04 on my Lenovo ThinkPad T480, with Intel UHD Graphics 620 and the latest UEFI updates.

I have an Akitio Node eGPU chassis with a Sapphire Radeon R9 Nano GPU.

I have an Iiyama G-Master GB2488HSU monitor connected to the laptop via HDMI and the eGPU via DisplayPort.

**Problem:**

When I run "sudo egpu-switcher switch internal", restart the computer, and then login again, The desktop background is always dotted with purple and green artifacts.

If I change the background to something else they disappear.

If I select the same background, without removing it from "Background" in "Settings", the artifacts are shown again.

If I remove the same background from "Background" and then add it again they disappear.

If I logout and login again the artifacts appear again, and I need to change the background again as described to get rid of them.

Sometimes artifacts appear on top of the sidebar. I am unable to get rid of these (perhaps there is a command to reload the sidebar). The only way to get rid of them is to logout and login again and hope they are not rendered there.

**Evidence:**

https://u.pcloud.link/publink/show?code=XZbEJtkZjtcCPoSatdFtjJlN8kF0NkVe8FRX
https://u.pcloud.link/publink/show?code=XZNEJtkZyUb1KqIWk47POK1fqKPgdYOTmNok

**Comment by JEdwardsD** [comment] 2020-05-28 15:35
I've got the same problem whenever I restart my computer and physically disconnect from the eGPU. I'm also running an Akitio Node via Thunderbolt 3 with an Nvidia graphics card.

**Comment by purplexed** [comment] 2020-06-03 13:40
Got the same issue too, but using Pop_Os 20.04 (Ubuntu based), Razer Core and RX580 on a Thinkpad X1 Carbon Gen.5

**Comment by tominglis** [comment] 2020-06-06 08:55
xorg.conf.internal:

Section "Module"
Load "modesetting"
EndSection

Section "Device"
Identifier "Device0"
Driver "intel"
BusID "0:2:0"
Option "AllowEmptyInitialConfiguration"
Option "AllowExternalGpus" "True"
EndSection

xorg.conf.egpu:

Section "Module"
Load "modesetting"
EndSection

Section "Device"
Identifier "Device0"
Driver "amdgpu"
BusID "9:0:0"
Option "AllowEmptyInitialConfiguration"
Option "AllowExternalGpus" "True"
EndSection

**Comment by hertg** [comment] 2020-06-06 09:26
Hi @tominglis, @purplexed, @JEdwardsD 

Did you specifically configure the internal configuration to use your Intel Integrated Graphics?
If so, there have been reports that the "intel" driver causes issues on Ubuntu 20.04 (see #33).
There was also feedback before 20.04, that defining a specific internal GPU causes trouble in some cases and it's preferrable to let X11 figure it out themselves on what GPU to use when not connected to the eGPU.

Generally, i wouldn't recommend defining a specific GPU for internal, that's why I've made this setting optional a few versions ago. I have also added a `(not recommended)` hint in the `Would you like to define a specific INTERNAL GPU? [y/N]:` configuration step now.

So a possible solution for you guys might be to reconfigure egpu-switcher and answering the configuration step above with the default `N` option. Please follow the steps below to fully reconfigure your egpu-switcher (This requires you to be connected to the eGPU).

```sh
# this purges the generated xorg.conf.* files 
# and removes your /etc/egpu-switcher/egpu-switcher.conf.
sudo egpu-switcher cleanup --hard

# Re-run the setup
sudo egpu-switcher setup
```

I am closing the issue now, as the artifcats are most likely an issue with the intel driver. Additionally i've updated the readme to mention that setting a specific internal GPU is not recommended and added links to this and other related issues.

**Closed by hertg** 2020-06-06 09:26 UTC

**Comment by tominglis** [comment] 2020-06-08 10:03
OK thanks, I'll try this and see if it helps.

I did not know about the earlier issue with specifying the internal gpu and must have ignored your warning text! :-)

**Comment by tominglis** [comment] 2020-06-08 13:55
I can confim that this seems to have resolved the issues I had.

**Comment by purplexed** [comment] 2020-06-09 22:10
I can confirm this solution works for me too
